"use client";

/* oxlint-disable i18next/no-literal-string */

import { Calendar, Clock, FileText, Printer } from "lucide-react";

import { MarkdownRenderer } from "~/components/report/MarkdownRenderer";

interface JPMReportProps {
  /** Raw markdown text from the AI stream */
  content: string;
  /** Company/ticker name */
  ticker?: string;
  /** Company display name */
  companyName?: string;
  /** Timestamp when report was generated */
  generatedAt?: string;
}

/**
 * J.P. Morgan-style investment research report wrapper.
 *
 * Renders the full Markdown output from Kimi inside a professional
 * chrome: header bar with metadata, serif body, and export controls.
 */
export function JPMReport({
  content,
  ticker,
  companyName,
  generatedAt,
}: JPMReportProps) {
  const now = generatedAt
    ? new Date(generatedAt).toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
      })
    : new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
      });

  return (
    <div className="bg-background overflow-hidden rounded-xl border shadow-sm">
      {/* ── Header bar ── */}
      <div className="from-primary to-primary/80 text-primary-foreground flex items-center justify-between bg-gradient-to-r px-5 py-3">
        <div className="flex items-center gap-3">
          <FileText className="h-4 w-4 opacity-80" />
          <div>
            <p className="text-[10px] font-semibold tracking-widest uppercase opacity-80">
              Equity Research
            </p>
            <p className="text-sm font-semibold">
              {companyName || ticker || "Research Report"}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-4 text-[11px] opacity-80">
          <span className="flex items-center gap-1">
            <Calendar className="h-3 w-3" />
            {now}
          </span>
          <span className="flex items-center gap-1">
            <Clock className="h-3 w-3" />
            {new Date().toLocaleTimeString("en-US", {
              hour: "2-digit",
              minute: "2-digit",
            })}
          </span>
          <button
            type="button"
            onClick={() => window.print()}
            className="border-primary-foreground/20 hover:bg-primary-foreground/10 flex items-center gap-1 rounded-md border px-2 py-1 text-[10px] transition"
          >
            <Printer className="h-3 w-3" />
            Export
          </button>
        </div>
      </div>

      {/* ── Ticker badge ── */}
      {ticker && (
        <div className="border-b px-5 py-2">
          <span className="bg-primary/10 text-primary inline-block rounded-full px-3 py-0.5 font-mono text-xs font-semibold">
            {ticker}
          </span>
          <span className="text-muted-foreground ml-2 text-[11px]">
            For research purposes only · Not investment advice
          </span>
        </div>
      )}

      {/* ── Report body ── */}
      <div className="jpm-report-body px-5 py-6">
        <MarkdownRenderer content={content} className="prose-jpm max-w-none" />
      </div>

      {/* ── Footer ── */}
      <div className="bg-muted/20 border-t px-5 py-3">
        <p className="text-muted-foreground/60 text-[10px] leading-relaxed">
          This report was generated by AI for informational and research
          purposes only. It does not constitute investment advice, a
          recommendation, or an offer to buy or sell any security. Verify all
          data independently before making investment decisions. Past
          performance is not indicative of future results.
        </p>
      </div>
    </div>
  );
}
