import {
  BillingDiscountType,
  BillingModel,
  BillingPlan,
  BillingType,
  RecurringInterval,
} from "../../../types";

import type { BillingConfig } from "../../../config";

export const config: BillingConfig = {
  plans: [
    {
      id: BillingPlan.FREE,
      name: "plan.free.name",
      description: "plan.free.description",
      badge: null,
      features: ["FEATURE_1", "FEATURE_2"],
      limits: {
        projects: 3,
        members: 1,
        storage: null,
      },
      variants: [
        {
          id: "free-lifetime",
          type: BillingType.FLAT,
          cost: 0,
          custom: false,
          currency: "usd",
          hidden: false,
          model: BillingModel.ONE_TIME,
        },
        {
          id: "free-monthly",
          type: BillingType.FLAT,
          cost: 0,
          custom: false,
          currency: "usd",
          hidden: false,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.MONTH,
        },
        {
          id: "free-yearly",
          type: BillingType.FLAT,
          cost: 0,
          custom: false,
          currency: "usd",
          hidden: false,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.YEAR,
        },
      ],
    },
    {
      id: BillingPlan.PRO,
      name: "plan.pro.name",
      description: "plan.pro.description",
      badge: "plan.pro.badge",
      features: ["FEATURE_1", "FEATURE_2", "FEATURE_3", "FEATURE_4"],
      limits: {
        projects: 10,
        members: 5,
      },
      variants: [
        {
          id: "pro-one-time",
          type: BillingType.FLAT,
          cost: 19900,
          custom: false,
          currency: "usd",
          hidden: false,
          model: BillingModel.ONE_TIME,
        },
        {
          id: "pro-monthly",
          type: BillingType.FLAT,
          cost: 1900,
          custom: false,
          currency: "usd",
          hidden: false,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.MONTH,
          trialDays: 7,
        },
        {
          id: "pro-yearly",
          type: BillingType.FLAT,
          cost: 19000, // Higher than monthly * 12 to test recurring discount
          custom: false,
          currency: "usd",
          hidden: false,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.YEAR,
          trialDays: 7,
        },
        {
          id: "pro-monthly-hidden",
          type: BillingType.FLAT,
          cost: 1900,
          custom: false,
          currency: "usd",
          hidden: true,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.MONTH,
        },
      ],
    },
    {
      id: BillingPlan.BUSINESS,
      name: "plan.business.name",
      description: "plan.business.description",
      badge: null,
      features: [
        "FEATURE_1",
        "FEATURE_2",
        "FEATURE_3",
        "FEATURE_4",
        "FEATURE_5",
      ],
      variants: [
        {
          id: "business-lifetime",
          type: BillingType.FLAT,
          custom: true,
          label: "common:contactUs",
          href: "/contact",
          hidden: false,
          model: BillingModel.ONE_TIME,
        },
        {
          id: "business-monthly",
          type: BillingType.FLAT,
          custom: true,
          label: "common:contactUs",
          href: "/contact",
          hidden: false,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.MONTH,
        },
        {
          id: "business-yearly",
          type: BillingType.FLAT,
          custom: true,
          label: "common:contactUs",
          href: "/contact",
          hidden: false,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.YEAR,
        },
      ],
    },
  ],
  discounts: [
    {
      code: "50OFF",
      type: BillingDiscountType.PERCENT,
      off: 50,
      appliesTo: ["pro-monthly", "pro-yearly"],
    },
    {
      code: "100OFF",
      type: BillingDiscountType.AMOUNT,
      off: 1000,
      appliesTo: ["pro-monthly"],
    },
    {
      code: "10OFF",
      type: BillingDiscountType.PERCENT,
      off: 10,
      appliesTo: ["pro-yearly"],
    },
  ],
};

export const ACTIVE_SUBSCRIPTION_STATUSES = ["active", "trialing"] as const;
