import os
import urllib.parse
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from openai import OpenAI
from pydantic import BaseModel, Field
import requests


# ── Shared Analysis Contract ─────────────────────────────────────────────────
# Build-time generated methodology (no runtime readDisk dependency).
# Generated by: pnpm generate:skill-contract
# Source: skills/deep-dive/SKILL.md → packages/shared/src/skill-contract/
#
# One edit to the skill = regenerate = both outputs (website + plugin) change.

CONTRACT_DIR = (
    Path(__file__).resolve().parent.parent.parent
    / "packages"
    / "shared"
    / "src"
    / "skill-contract"
)


def _load_text(filename: str, fallback: str) -> str:
    """Load a build-time generated file. Falls back to fallback if missing."""
    try:
        return (CONTRACT_DIR / filename).read_text(encoding="utf-8").strip()
    except FileNotFoundError:
        return fallback


def _load_json(filename: str, fallback: dict) -> dict:
    """Load a build-time generated JSON file. Falls back to fallback if missing."""
    import json

    try:
        return json.loads((CONTRACT_DIR / filename).read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError):
        return fallback


# ── Inline fallback (used when JSON is missing/corrupt — safety rules must NEVER silently disappear) ──
_INLINE_HARD_RULES = """## SHARED HARD RULES (from analysis contract — applies to ALL modes)

1. **Entity Gate (MANDATORY).** Resolve input to exactly ONE verified listed entity before ANY analysis. Never analyze a blend. If ambiguous, STOP and ask.
2. **Never fabricate financial figures.** If a number can't be verified, say "Data unavailable — [what to verify]".
3. **Never output** target prices, buy/sell ratings, entry levels, stop levels, portfolio weights, position sizing, or personalized investment instructions.
4. **Conviction tier** (S/A/B/C/D/F) evaluates evidence quality only — not whether to buy, sell, hold, size, or allocate.
5. **Every quantitative claim** gets a date or period attached. Distinguish facts from estimates from opinion.
6. **GAAP first.** If citing non-GAAP, name the excluded items.
7. **Never substitute** a similarly-named company. If data is missing for the resolved entity, say so.
8. **Reports end with invalidation conditions**, not price targets.
9. **Never present** the report as a trade instruction. Never execute, place, or cancel orders.
10. **Cross-market A/H peers: sourced or stated absent.** When the methodology calls for A-share or H-share peer comparison, every listed peer MUST come from search results with a citable source (ETF holdings, filings, financial media). If no sourced A/H peer exists for a chain layer, write "No listed A-share/H-share pure play found in sources" — never fill the gap from memory. **Fabricating peer names is the same failure as fabricating financial figures (rule 2).**""".strip()

_INLINE_MODE_PERSPECTIVES: dict[str, dict[str, str]] = {
    "snapshot": {
        "label": "Investment snapshot: decide in 3 minutes whether the stock deserves deeper work",
        "focus": "Balance breadth vs depth. Cover thesis, valuation, risks, and catalysts at equal weight.",
        "emphasis": "overview, investmentThesis, decisionBrief",
    },
    "earnings": {
        "label": "Earnings review: focus on growth quality, margins, cash flow, and execution",
        "focus": "Deep-dive revenue trajectory, margin evolution, FCF conversion, and earnings surprise history.",
        "emphasis": "growthDrivers, profitability, topJudgments (margin/cash flow focus)",
    },
    "competition": {
        "label": "Competitive landscape: moat, substitution risk, pricing power, and industry position",
        "focus": "Analyze market share trends, moat durability, Porter's Five Forces, peer benchmarking.",
        "emphasis": "overview (competitive framing), risks (disruption/substitution), scenarioMatrix",
    },
    "risk": {
        "label": "Risk scan: valuation, balance sheet, cash flow, cyclicality, and crowded narrative risk",
        "focus": "Invert the analysis — lead with what can go wrong. Weight risks section 3x.",
        "emphasis": "risks (primary focus), valuation (downside scenarios), scenarioMatrix (bear case details)",
    },
    "poc": {
        "label": "Tracking plan: convert the thesis into 30-90 day measurable validation points",
        "focus": "Focus on the watchlist and monitorPanel sections. Light on narrative, heavy on actionable metrics.",
        "emphasis": "watchlist, monitorPanel, nextSteps, evidenceNeeds",
    },
}

SKILL_METHODODOLOGY = _load_text(
    "generated_methodology.txt",
    (
        "## ANALYSIS CONTRACT — REDUCED (methodology unavailable)\n"
        "The detailed methodology file could not be loaded. Apply shared hard"
        " rules only. Do not invent methodology detail to fill the gap."
    ),
)

SHARED_HARD_RULES: str = _load_json("hard_rules.json", {}).get("rules", "") or _INLINE_HARD_RULES

MODE_PERSPECTIVES: dict[str, dict[str, str]] = _load_json(
    "mode_perspectives.json", {}
) or _INLINE_MODE_PERSPECTIVES


app = FastAPI(title="Aireseach Business Report Agent")
app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("CORS_ALLOW_ORIGINS", "*").split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

REPORT_MODE = os.getenv("REPORT_MODE", "deep_research")

DEEP_RESEARCH_API_KEY = os.getenv("PERPLEXITY_API_KEY") or os.getenv("OPENAI_API_KEY")
DEEP_RESEARCH_BASE_URL = os.getenv("AGENT_BASE_URL", "https://api.perplexity.ai")
DEEP_RESEARCH_MODEL = os.getenv("AGENT_MODEL", "sonar-deep-research")

LLM_API_KEY = os.getenv("LLM_API_KEY") or os.getenv("DEEPSEEK_API_KEY")
LLM_BASE_URL = os.getenv("LLM_BASE_URL", "https://api.deepseek.com/v1")
LLM_MODEL = os.getenv("LLM_MODEL", "deepseek-chat")

# Kimi (Moonshot AI) — OpenAI-compatible, 1M context (K3)
KIMI_API_KEY = os.getenv("KIMI_API_KEY", "")
KIMI_BASE_URL = os.getenv("KIMI_BASE_URL", "https://api.moonshot.ai/v1")

# Alias normalization: legacy "k3" env → canonical "kimi-k3"
_KIMI_MODEL_RAW = os.getenv("KIMI_MODEL", "kimi-k3").strip()
KIMI_MODEL = "kimi-k3" if _KIMI_MODEL_RAW in ("k3", "kimi-k3") else _KIMI_MODEL_RAW

# K3 reasoning effort: low | high | max. Default "high" to control cost.
# "max" reserved for explicit deep-dive mode.
KIMI_REASONING_EFFORT = os.getenv("KIMI_REASONING_EFFORT", "high")

JINA_API_KEY = os.getenv("JINA_API_KEY", "")
JINA_SEARCH_BASE_URL = os.getenv("JINA_SEARCH_BASE_URL", "https://s.jina.ai/")
SEARCH_TIMEOUT_SECONDS = int(os.getenv("SEARCH_TIMEOUT_SECONDS", "20"))
SEARCH_CONTEXT_CHARS = int(os.getenv("SEARCH_CONTEXT_CHARS", "12000"))

# Serenity reference files
SERENITY_REF_DIR = os.path.join(os.path.dirname(__file__), "references")

HOSTED_KEY_BALANCE_ERROR = (
    "Hosted model credits are temporarily unavailable. Recharge the platform key "
    "or enter your own compatible API key, then run the analysis again."
)


def normalize_model_error(exc: Exception) -> str:
    message = str(exc)
    lowered = message.lower()
    if (
        "insufficient balance" in lowered
        or "402" in lowered
        or "quota" in lowered
        or "billing" in lowered
        or "credit" in lowered
    ):
        return HOSTED_KEY_BALANCE_ERROR
    return message


class ReportRequest(BaseModel):
    target: str = Field(..., min_length=1, description="Company, asset, or industry to analyze")
    analysis_years: int = Field(5, ge=1, le=10, description="Lookback window in years")
    analysis_lens: str = Field("Comprehensive", description="Primary analysis lens")
    mode: str = Field("snapshot", description="Analysis mode: snapshot, earnings, competition, risk, poc")
    report_mode: Optional[str] = Field(None, description="deep_research or jina_llm")
    api_key: Optional[str] = Field(None, description="Model API key for this request")
    base_url: Optional[str] = Field(None, description="OpenAI-compatible API base URL")
    model: Optional[str] = Field(None, description="Model name")
    jina_api_key: Optional[str] = Field(None, description="Optional Jina AI API key")
    language: Optional[str] = Field("en", description="Report output language code (en, zh-TW, zh-CN, ja, ko, etc.)")


class SerenityRequest(BaseModel):
    ticker: str = Field(..., min_length=1, max_length=10, description="Stock ticker symbol, e.g. NVDA, AXTI, LITE")
    mode: str = Field("single", description="single, portfolio, or sector")
    tickers: Optional[list[str]] = Field(None, description="List of tickers for portfolio mode")
    api_key: Optional[str] = Field(None, description="Model API key")
    base_url: Optional[str] = Field(None, description="OpenAI-compatible API base URL")
    model: Optional[str] = Field(None, description="Model name")
    language: Optional[str] = Field("en", description="Output language")
    skill_prompt: Optional[str] = Field(None, description="Custom system prompt for the skill")
    report_mode: Optional[str] = Field(None, description="kimi_llm, kimi_k3, or default")


class EarningsRequest(BaseModel):
    ticker: str = Field(..., min_length=1, max_length=10, description="Stock ticker symbol")
    quarter: Optional[str] = Field(None, description="Specific quarter to analyze, e.g. 'Q2 2026'. Defaults to latest.")
    api_key: Optional[str] = Field(None, description="Model API key")
    base_url: Optional[str] = Field(None, description="OpenAI-compatible API base URL")
    model: Optional[str] = Field(None, description="Model name")
    language: Optional[str] = Field("en", description="Output language")
    report_mode: Optional[str] = Field(None, description="kimi_llm, kimi_k3, or default")


class PostEarningsMoveRequest(BaseModel):
    ticker: str = Field(..., min_length=1, max_length=10, description="Stock ticker symbol")
    move_pct: Optional[float] = Field(None, description="Post-earnings price move percentage, e.g. -15.0")
    quarter: Optional[str] = Field(None, description="Quarter that triggered the move, e.g. 'Q2 2026'")
    api_key: Optional[str] = Field(None, description="Model API key")
    base_url: Optional[str] = Field(None, description="OpenAI-compatible API base URL")
    model: Optional[str] = Field(None, description="Model name")
    language: Optional[str] = Field("en", description="Output language")
    report_mode: Optional[str] = Field(None, description="kimi_llm, kimi_k3, or default")


def _build_system_prompt(mode: str = "snapshot") -> str:
    """Build system prompt from shared analysis contract.

    Assembles: SHARED_HARD_RULES + SKILL_METHODOLOGY + mode perspective +
    website-specific output format. One edit to the skill = prompt changes.
    """
    perspective = MODE_PERSPECTIVES.get(mode, MODE_PERSPECTIVES.get("snapshot", {}))
    perspective_section = ""
    if perspective:
        perspective_section = f"""
## ANALYSIS MODE
{perspective.get('label', 'Investment snapshot')}

### Focus Areas
{perspective.get('focus', '')}

### Sections to Emphasize
{perspective.get('emphasis', '')}
"""

    return f"""You are a senior equity research analyst at a top-tier investment bank. Your analysis style is institutional-grade: evidence-first, quantitative, structured, and written for sophisticated investors.

{SHARED_HARD_RULES}

## ANALYSIS METHODOLOGY (from shared skill contract)

{SKILL_METHODODOLOGY}
{perspective_section}
## WEBSITE-SPECIFIC OUTPUT FORMAT

The methodology above defines the canonical output structure. For the website report, produce the following sections (mapped to the methodology):

### 0. ENTITY LOCK
- Resolved company name, ticker, exchange, GICS sector/industry
- Data timestamp and source confidence level (High / Medium / Low)
- For industry/theme targets: state "Industry Mode" and define universe construction

### 1. INVESTMENT THESIS (3-5 sentences max)
- Lead with the conclusion. State the directional view and the single most important driver.
- Include: what the market is missing, why now, and what makes this non-consensus.
- End with a one-line conviction statement.

### 2. KEY DATA TABLE
Present a Markdown table with these rows (use actual numbers, "N/A" if unavailable):

| Metric | Current | YoY Change | Peer Median | Source |
|--------|---------|------------|-------------|--------|
| Revenue | | | | |
| Gross Margin | | | | |
| Operating Margin | | | | |
| Net Margin | | | | |
| FCF | | | | |
| P/E | | | | |
| EV/EBITDA | | | | |
| ROE | | | | |
| Debt/Equity | | | | |

### 3–6. SIX LENSES (from methodology above)
Follow the six-lens structure defined in the methodology. Each lens ends with:
- Lens judgment (one numeric, falsifiable conclusion)
- How to read this number (source, basis, timestamp, blind spot)

### 7. CATALYST CALENDAR
List dated events for the next 12 months:
- Earnings dates, guidance updates
- Regulatory decisions, product launches
- Industry conferences, management changes
- Macro events (rate decisions, policy shifts)

### 8. RISK MATRIX
Rank top 5 risks by (Impact × Probability):
| Risk | Impact (1-5) | Probability (1-5) | Score | Mitigation |
|------|-------------|-------------------|-------|------------|

### 9. THREE FALSIFIABLE JUDGMENTS (from methodology)
Exactly three judgments, each with: falsifiable sentence, numeric anchor, supporting evidence, "Wrong if:" with numeric trigger.

### 10. THESIS INVALIDATION CONDITIONS (from methodology)
2–4 specific, measurable conditions with numeric thresholds.

### 11. MONITOR PANEL (from methodology)
3–6 row table: Metric | Current | Trigger | Tolerance | Frequency | Source
Plus machine-readable monitor JSON block.

### 12. CONVICTION TIER (from methodology)
S/A/B/C/D/F — thesis quality score only, not a buy/sell recommendation.

### 13. EVIDENCE SPINE
5–8 key sources with date, full URL, and the claim each supports.
Mark data confidence: 🟢 Verified | 🟡 Partial | 🔴 Unverified

### 14. DISCLAIMER
"Decision-support analysis only. Not investment advice. Verify all data independently before making investment decisions."

## WRITING STYLE
- Lead every section with the conclusion, then support with evidence
- Use specific numbers, not vague qualifiers ("revenue grew 12.3% YoY" not "revenue grew significantly")
- Professional, institutional tone — no emoji, no casual language
- When data is unavailable, write "Data unavailable — [what to verify]" — never fabricate
- Preserve source names, dates, and URLs
"""


def validate_target(target: str) -> str:
    cleaned_target = target.strip()
    if not cleaned_target:
        raise HTTPException(status_code=400, detail="Enter a research target.")
    return cleaned_target


def clean_optional_text(value: Optional[str]) -> str:
    return value.strip() if value else ""


def validate_header_value(value: str, label: str) -> str:
    if not value:
        return value
    try:
        value.encode("ascii")
    except UnicodeEncodeError as exc:
        raise HTTPException(
            status_code=400,
            detail=(
                f"{label} contains non-ASCII characters. Paste the raw key only, "
                "without quotes, notes, emoji, or extra text."
            ),
        ) from exc
    return value


def get_llm_config(request: ReportRequest):
    report_mode = request.report_mode or REPORT_MODE
    request_api_key = validate_header_value(clean_optional_text(request.api_key), "API Key")
    request_base_url = clean_optional_text(request.base_url)
    request_model = clean_optional_text(request.model)

    # Kimi mode — K3 (2.8T, 1M context, always-on thinking)
    # "kimi_k3" forces kimi-k3; "kimi_llm" reads KIMI_MODEL env (normalized).
    if report_mode in ("kimi_llm", "kimi_k3"):
        api_key = validate_header_value(request_api_key or KIMI_API_KEY, "API Key")
        if not api_key:
            raise HTTPException(
                status_code=400,
                detail="Enter your Kimi API key to generate this report.",
            )
        model_override = "kimi-k3" if report_mode == "kimi_k3" else KIMI_MODEL
        return api_key, request_base_url or KIMI_BASE_URL, request_model or model_override, report_mode

    if report_mode == "jina_llm":
        api_key = validate_header_value(request_api_key or LLM_API_KEY, "API Key")
        if not api_key:
            raise HTTPException(
                status_code=400,
                detail="Enter your model API key to generate this report.",
            )
        return api_key, request_base_url or LLM_BASE_URL, request_model or LLM_MODEL, report_mode

    api_key = validate_header_value(request_api_key or DEEP_RESEARCH_API_KEY, "API Key")
    if not api_key:
        raise HTTPException(
            status_code=400,
            detail="Enter your Perplexity or compatible model API key to generate this report.",
        )
    return (
        api_key,
        request_base_url or DEEP_RESEARCH_BASE_URL,
        request_model or DEEP_RESEARCH_MODEL,
        report_mode,
    )


def fetch_search_context(target: str, analysis_years: int, analysis_lens: str, jina_api_key: str = ""):
    query = (
        f"{target} market share competitive analysis financial filings industry report 2026 "
        f"last {analysis_years} years {analysis_lens}"
    )
    encoded_query = urllib.parse.quote(query)
    jina_url = f"{JINA_SEARCH_BASE_URL}{encoded_query}"
    headers = {}
    if jina_api_key:
        headers["Authorization"] = f"Bearer {jina_api_key}"

    try:
        response = requests.get(
            jina_url,
            headers=headers,
            timeout=SEARCH_TIMEOUT_SECONDS,
        )
        if response.status_code == 401:
            return (
                "",
                "Jina Search returned 401 Unauthorized. The platform search key may need attention, "
                "or the user can switch to Perplexity Deep Research mode.",
            )
        if response.status_code >= 400:
            return "", f"Jina Search returned HTTP {response.status_code}: {response.text[:300]}"
        return response.text[:SEARCH_CONTEXT_CHARS], ""
    except requests.exceptions.RequestException as exc:
        return "", f"Jina Search request failed: {exc}"


def build_messages(
    target: str,
    analysis_years: int,
    analysis_lens: str,
    search_context: str = "",
    search_warning: str = "",
    language: str = "en",
    mode: str = "snapshot",
):
    report_brief = (
        f"Research target: {target}\n"
        f"Lookback window: last {analysis_years} years\n"
        f"Primary analysis lens: {analysis_lens}\n\n"
        "Organize the output like a professional investment research product: "
        "ENTITY LOCK first, then three falsifiable judgments, evidence-backed lens analysis, "
        "thesis invalidation conditions, and a machine-readable monitor panel at the end."
    )

    # Serenity supply-chain bottleneck methodology
    serenity_instruction = ""
    if "Serenity" in analysis_lens or "bottleneck" in analysis_lens.lower():
        serenity_instruction = """\n\nApply the Serenity (@aleabitoreddit) supply-chain bottleneck analysis framework:

CORE PRINCIPLE: Don't buy the obvious "shovel seller" — trace the supply chain upstream to find the single chokepoint that a downstream buyer will pay anything to keep flowing. The further upstream and the smaller the market cap, the more underpriced the bottleneck.

ANALYSIS STRUCTURE:
1. Supply Chain Map: Map the full chain from end-demand (hyperscaler capex, AI infrastructure, etc.) down to raw materials/feedstock. Identify every hop.
2. Bottleneck Identification: At each hop, ask "if this layer stopped shipping, what breaks downstream, and is there a second source?" The fewer substitutes and bigger the downstream dependency, the better the asymmetry.
3. 14-Point Checklist:
   - Bottleneck? Is it sole/near-sole-source with pricing power?
   - Upstream & cheap? Small % of downstream BOM so buyers pay through?
   - Chain fluency? Can you map the exact BOM chain?
   - Demand driver? TAM expanding on AI/tech capex, not legacy market?
   - Contracts & counterparty? Signed multi-year, creditworthy tenant?
   - Real margins? GAAP margins support quality claim?
   - Financing quality? Any ATM/SBC overhang?
   - Stage? Pre-volume-ramp mispriced on TTM revenue?
   - Catalyst? Dated catalyst within tradable window?
   - Market cap headroom? Small enough for institutional re-rating?
   - Validation lag? Analyst coverage still behind supply-chain evidence?
   - Risk & sizing? How binary is it?
   - Macro overlay? Rate path / tariff / war regime help or hurt?
4. Key Metrics Dashboard: Market share, revenue/profit growth, valuation context, cash flow, competitive intensity, with data confidence levels.
5. Thesis Quality View: evidence-backed judgment quality, 3 black swan or grey rhino risks, invalidation conditions, and monitorable metrics. Do not output target prices, buy/sell ratings, position sizing, or portfolio allocation suggestions.

IMPORTANT: This is analysis, not financial advice. Never generate, place, or cancel trade orders. Present as a lens for asking better questions."""

    if search_context:
        user_content = (
            f"{report_brief}\n\n"
            "Below are public-source snippets returned by Jina AI real-time search. "
            "Prioritize this material, preserve verifiable sources, dates, and links, "
            "and clearly mark anything as an inference or needing verification when evidence is thin.\n\n"
            f"{search_context}\n\n"
            f"Generate a deep business report for: {target}.{serenity_instruction}"
        )
    elif search_warning:
        user_content = (
            f"{report_brief}\n\n"
            f"Real-time search failed: {search_warning}\n\n"
            "Generate a structurally complete business analysis report without fabricating current market data. "
            'For 2026 data, market share, news, or filings, clearly mark "Needs real-time verification".\n\n'
            f"Generate a deep business report for: {target}.{serenity_instruction}"
        )
    else:
        user_content = f"{report_brief}\n\nGenerate a deep business report for: {target}.{serenity_instruction}"

    lang_instruction = ""
    lang_names = {
        "zh-TW": "Traditional Chinese (繁體中文)",
        "zh-CN": "Simplified Chinese (简体中文)",
        "ja": "Japanese (日本語)",
        "ko": "Korean (한국어)",
        "es": "Spanish",
        "de": "German",
        "fr": "French",
        "en": "English",
    }
    if language and language != "en":
        lang_name = lang_names.get(language, language)
        lang_instruction = f"\n\nIMPORTANT: Write the ENTIRE report in {lang_name}. All section titles, analysis, evidence descriptions, and conclusions must be in {lang_name}."

    return [
        {"role": "system", "content": _build_system_prompt(mode) + lang_instruction},
        {"role": "user", "content": user_content},
    ]


def build_report_request(request: ReportRequest):
    target = validate_target(request.target)
    analysis_years = max(1, min(10, request.analysis_years))
    analysis_lens = request.analysis_lens.strip() if request.analysis_lens else "综合"
    api_key, base_url, model, report_mode = get_llm_config(request)
    search_context = ""
    search_warning = ""
    if report_mode == "jina_llm":
        request_jina_key = validate_header_value(
            clean_optional_text(request.jina_api_key),
            "Jina API Key",  # redline-allow: internal config label, not user-visible
        )
        search_context, search_warning = fetch_search_context(
            target,
            analysis_years,
            analysis_lens,
            validate_header_value(request_jina_key or JINA_API_KEY, "Jina API Key"),  # redline-allow: internal config label, not user-visible
        )
    return (
        api_key,
        base_url,
        model,
        build_messages(target, analysis_years, analysis_lens, search_context, search_warning, request.language or "en", request.mode),
        search_warning,
    )


# ──────────────────────────────────────────────
# Serenity Supply-Chain Analysis
# ──────────────────────────────────────────────

def load_serenity_references() -> dict[str, str]:
    """Load Serenity reference files from disk."""
    refs = {}
    for name in ["methodology.md", "theses.md", "track-record.md", "articles.md"]:
        path = os.path.join(SERENITY_REF_DIR, name)
        try:
            with open(path, encoding="utf-8") as f:
                refs[name] = f.read()
        except FileNotFoundError:
            refs[name] = ""
    return refs


def _build_serenity_system_prompt(custom_prompt: Optional[str] = None) -> str:
    """Build Serenity system prompt with shared hard rules baseline."""
    if custom_prompt:
        return f"{SHARED_HARD_RULES}\n\n{custom_prompt}"
    return f"""{SHARED_HARD_RULES}

You are Serenity's AI analytical assistant — a supply-chain bottleneck analyst modeled after @aleabitoreddit's methodology.

Your job: evaluate stocks through the lens of upstream supply-chain chokepoints, NOT through traditional fundamental or technical analysis alone.

CORE PRINCIPLE: Do not stop at the obvious "shovel seller" (NVDA). Trace the supply chain as far upstream as possible and identify single points of failure that downstream buyers depend on. The further upstream and less visible the node, the more likely the market narrative is incomplete.

ANALYSIS STRUCTURE:
1. Supply Chain Map — Map the full chain from end-demand (hyperscaler capex, AI infra) down to raw materials/feedstock. Identify every hop.
2. Bottleneck Identification — At each hop: "if this layer stopped shipping, what breaks downstream, and is there a second source?"
3. Serenity's 14-Point Checklist — Evaluate: Bottleneck?, Upstream & cheap?, Chain fluency?, Demand driver?, Contracts & counterparty?, Real margins?, Financing quality?, Stage?, Catalyst?, Market cap headroom?, Validation lag?, Risk & sizing?, Macro overlay?, Position?
4. Thesis Assessment — Cross-reference against Serenity's known theses and track record.
5. Thesis Quality View — evidence quality tier, bull/bear cases, invalidation conditions, and monitorable metrics. This tier evaluates the thesis, not whether to buy, sell, hold, size, or allocate.

CRITICAL RULES:
- This is DECISION-SUPPORT ONLY. Never auto-trade, never place orders.
- Always state disclaimers: self-reported returns, survivorship bias, thesis decay.
- Flag if Serenity has a known view on this ticker (check the theses provided).
- If Serenity never covered it, run the 14-point checklist on a fresh name.
- Write professionally, no emoji, evidence-led.
"""


def build_serenity_messages(
    ticker: str,
    mode: str,
    tickers: Optional[list[str]],
    refs: dict[str, str],
    language: str = "en",
    custom_prompt: Optional[str] = None,
) -> list[dict[str, str]]:
    """Build messages for Serenity supply-chain analysis."""
    # Truncate theses to fit context window (keep first 30k chars)
    theses_context = refs.get("theses.md", "")[:30000]
    methodology_context = refs.get("methodology.md", "")[:15000]
    articles_context = refs.get("articles.md", "")[:8000]
    track_record_context = refs.get("track-record.md", "")[:8000]

    context = f"""
## Serenity's Known Theses (merged knowledge base)
{theses_context}

## Serenity's Methodology & 14-Point Checklist
{methodology_context}

## Serenity's Long-Form Articles
{articles_context}

## Serenity's Track Record & Calibration
{track_record_context}
"""

    lang_instruction = ""
    lang_names = {
        "zh-TW": "Traditional Chinese (繁體中文)",
        "zh-CN": "Simplified Chinese (简体中文)",
        "ja": "Japanese (日本語)",
        "ko": "Korean (한국어)",
        "es": "Spanish",
        "de": "German",
        "fr": "French",
        "en": "English",
    }
    if language and language != "en":
        lang_name = lang_names.get(language, language)
        lang_instruction = f"\n\nIMPORTANT: Write the ENTIRE analysis in {lang_name}."

    if mode == "portfolio" and tickers:
        user_content = (
            f"Analyze the following portfolio through Serenity's supply-chain lens:\n\n"
            f"Tickers: {', '.join(tickers)}\n\n"
            f"For each ticker:\n"
            f"1. Check if Serenity has a known thesis (reference the knowledge base below)\n"
            f"2. Map its position in the AI/semiconductor supply chain\n"
            f"3. Rate bottleneck strength (Strong / Moderate / Weak / None)\n"
            f"4. Flag agreements and conflicts with Serenity's views\n\n"
            f"Then provide a summary: which names have the strongest bottleneck thesis, "
            f"which are missing from the portfolio, and prioritized discussion list.\n\n"
            f"--- REFERENCE DATA ---\n{context}"
        )
    elif mode == "sector":
        user_content = (
            f"Form a forward sector view on the AI/semiconductor supply chain, "
            f"focusing on: {ticker}\n\n"
            f"Use Serenity's thematic threads: photonics/CPO, memory/HBM supercycle, "
            f"neocloud financing quality, power/grid, defense, AI-agent hardware.\n\n"
            f"Pull relevant theses from the knowledge base. Note leading indicators. "
            f"State the view with confidence level and dated evidence.\n\n"
            f"--- REFERENCE DATA ---\n{context}"
        )
    else:
        user_content = (
            f"Evaluate **{ticker}** through Serenity's supply-chain bottleneck lens.\n\n"
            f"Steps:\n"
            f"1. Look up {ticker} in Serenity's known theses below. Note his stance, conviction tier, how it evolved.\n"
            f"2. If he never covered it, run the 14-point checklist from methodology.md on this fresh name.\n"
            f"3. Map its position in the AI/semiconductor supply chain.\n"
            f"4. Sanity-check timeliness — flag if his view is dated.\n"
            f"5. Present: Serenity's view (if any), supply-chain read, bull/bear case, risks.\n\n"
            f"--- REFERENCE DATA ---\n{context}"
        )

    # Use custom prompt if provided, otherwise use default Serenity system prompt
    system_prompt = _build_serenity_system_prompt(custom_prompt)

    return [
        {"role": "system", "content": system_prompt + lang_instruction},
        {"role": "user", "content": user_content},
    ]


@app.post("/api/analyze_serenity")
async def analyze_serenity(request: SerenityRequest):
    ticker = request.ticker.strip().upper()
    if not ticker:
        raise HTTPException(status_code=400, detail="Enter a ticker symbol.")

    api_key = validate_header_value(clean_optional_text(request.api_key), "API Key")
    if not api_key:
        api_key = LLM_API_KEY
    if not api_key:
        raise HTTPException(status_code=400, detail="Enter your model API key.")

    report_mode = request.report_mode or ""
    if report_mode in ("kimi_llm", "kimi_k3"):
        base_url = clean_optional_text(request.base_url) or KIMI_BASE_URL
        model = clean_optional_text(request.model) or ("kimi-k3" if report_mode == "kimi_k3" else KIMI_MODEL)
    else:
        base_url = clean_optional_text(request.base_url) or LLM_BASE_URL
        model = clean_optional_text(request.model) or LLM_MODEL
    language = request.language or "en"

    refs = load_serenity_references()
    tickers = request.tickers if request.mode == "portfolio" and request.tickers else None

    # Use custom skill_prompt if provided, otherwise use default Serenity prompt
    if request.skill_prompt:
        messages = build_serenity_messages(ticker, request.mode, tickers, refs, language, custom_prompt=request.skill_prompt)
    else:
        messages = build_serenity_messages(ticker, request.mode, tickers, refs, language)

    def stream():
        try:
            client = OpenAI(api_key=api_key, base_url=base_url)
            kwargs: dict = dict(
                model=model,
                messages=messages,
                stream=True,
                max_tokens=16384,
            )
            if report_mode in ("kimi_llm", "kimi_k3"):
                kwargs["extra_body"] = {"reasoning_effort": KIMI_REASONING_EFFORT}
            response = client.chat.completions.create(**kwargs)
            for chunk in response:
                delta = chunk.choices[0].delta.content
                if delta:
                    yield delta
        except Exception as exc:
            yield f"\n\nAnalysis failed: {normalize_model_error(exc)}"

    return StreamingResponse(stream(), media_type="text/markdown; charset=utf-8")


@app.post("/api/generate_report")
async def generate_report(request: ReportRequest):
    validate_target(request.target)

    try:
        api_key, base_url, model, messages, search_warning = build_report_request(request)
        report_mode = request.report_mode or REPORT_MODE
        client = OpenAI(api_key=api_key, base_url=base_url)
        kwargs: dict = dict(
            model=model,
            messages=messages,
            stream=False,
            max_tokens=16384,
        )
        if report_mode in ("kimi_llm", "kimi_k3"):
            kwargs["extra_body"] = {"reasoning_effort": KIMI_REASONING_EFFORT}
        response = client.chat.completions.create(**kwargs)
        report_content = response.choices[0].message.content
        if search_warning:
            report_content = f"> Search note: {search_warning}\n\n{report_content}"
        return {"status": "success", "data": report_content}
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.post("/api/generate_report_stream")
async def generate_report_stream(request: ReportRequest):
    validate_target(request.target)
    try:
        api_key, base_url, model, messages, search_warning = build_report_request(request)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    def stream_report():
        try:
            if search_warning:
                yield f"> Search note: {search_warning}\n\n"
            report_mode = request.report_mode or REPORT_MODE
            client = OpenAI(api_key=api_key, base_url=base_url)
            kwargs: dict = dict(
                model=model,
                messages=messages,
                stream=True,
                max_tokens=16384,
            )
            if report_mode in ("kimi_llm", "kimi_k3"):
                kwargs["extra_body"] = {"reasoning_effort": KIMI_REASONING_EFFORT}
            response = client.chat.completions.create(**kwargs)
            for chunk in response:
                delta = chunk.choices[0].delta.content
                if delta:
                    yield delta
        except Exception as exc:
            yield f"\n\nReport generation failed: {exc}"

    return StreamingResponse(stream_report(), media_type="text/markdown; charset=utf-8")


# ──────────────────────────────────────────────
# Earnings Deep Dive Analysis
# ──────────────────────────────────────────────

def _build_earnings_system_prompt() -> str:
    """Build earnings system prompt with shared hard rules baseline."""
    return f"""{SHARED_HARD_RULES}

You are a senior equity research analyst at a top-tier investment bank, specializing in post-earnings analysis. Your job is to dissect quarterly earnings reports with surgical precision — every sentence must carry analytical weight and be anchored to specific numbers from the filing.

OUTPUT FORMAT: Return a single JSON object with the following structure. All text fields should use Markdown formatting. Use **bold** for key numbers and critical findings — these will be rendered with a highlighter visual effect.

IMPORTANT HIGHLIGHTER RULES:
- Wrap every critical data point, surprise metric, or key finding in **bold** — these get the yellow highlighter treatment
- Wrap negative surprises, red flags, and misses in **==double equals==** — these get the red highlighter treatment
- Wrap positive surprises, beats, and upgrades in **~~strikethrough~~** — these get the green highlighter treatment
- Every section must have at least 2 highlighted items

STRUCTURE:
{
  "earningsSnapshot": {
    "quarter": "Q2 2026",
    "reportDate": "2026-07-22",
    "epsActual": "$0.85",
    "epsEstimate": "$0.78",
    "epsSurprise": "+8.97% beat",
    "revenueActual": "$25.5B",
    "revenueEstimate": "$24.8B",
    "revenueSurprise": "+2.82% beat",
    "stockMoveAfterHours": "-15.2%",
    "verdict": "Miss on margins despite revenue beat — guidance cut spooked the market"
  },
  "revenueAnalysis": {
    "title": "Revenue & Growth Breakdown",
    "content": "<detailed markdown analysis>",
    "highlights": ["key finding 1", "key finding 2"],
    "sentiment": "positive|negative|mixed"
  },
  "marginAnalysis": { "title": "...", "content": "...", "highlights": [...], "sentiment": "..." },
  "cashFlowAnalysis": { "title": "...", "content": "...", "highlights": [...], "sentiment": "..." },
  "guidanceAnalysis": { "title": "...", "content": "...", "highlights": [...], "sentiment": "..." },
  "managementTone": { "title": "...", "content": "...", "highlights": [...], "sentiment": "..." },
  "analystReaction": { "title": "...", "content": "...", "highlights": [...], "sentiment": "..." },
  "keyTakeaways": ["Takeaway 1 with **bolded key number**", "..."],
  "watchNext": ["Metric to watch", "..."]
}

RULES:
- Use REAL financial terminology and specific numbers
- Every content field must have at least 2 **bolded** key data points
- Sentiment must accurately reflect whether the section is positive, negative, or mixed
- keyTakeaways: exactly 3-5 items, each with a bolded number
- watchNext: exactly 2-3 items
- Write professionally, no emoji, evidence-led
- If specific data is unavailable, note it clearly rather than fabricating
"""


def build_earnings_messages(
    ticker: str,
    quarter: Optional[str],
    language: str,
) -> list[dict[str, str]]:
    """Build messages for earnings deep-dive analysis."""
    quarter_str = quarter or "the most recent quarter"
    user_content = (
        f"Generate a comprehensive earnings deep-dive analysis for **{ticker}** ({quarter_str}).\n\n"
        f"Search for the latest earnings report, financial filings, earnings call transcripts, "
        f"and post-earnings stock price movement. Use real data from the most recent filing.\n\n"
        f"Analyze:\n"
        f"1. Revenue trajectory — segment breakdown, YoY/QoQ, geographic mix\n"
        f"2. Margin evolution — gross, operating, net, with specific drivers\n"
        f"3. Cash flow — FCF, capex, working capital, buybacks\n"
        f"4. Forward guidance — next quarter and full-year, any raises/cuts\n"
        f"5. Management tone — what they emphasized, hedged, or avoided\n"
        f"6. Market reaction — stock move, options implied move, analyst actions\n\n"
        f"Return the analysis as a JSON object following the system prompt schema."
    )

    lang_instruction = ""
    lang_names = {
        "zh-TW": "Traditional Chinese (繁體中文)",
        "zh-CN": "Simplified Chinese (简体中文)",
        "ja": "Japanese (日本語)",
        "ko": "Korean (한국어)",
        "es": "Spanish",
        "de": "German",
        "fr": "French",
        "en": "English",
    }
    if language and language != "en":
        lang_name = lang_names.get(language, language)
        lang_instruction = f"\n\nIMPORTANT: Write the ENTIRE analysis in {lang_name}."

    return [
        {"role": "system", "content": _build_earnings_system_prompt() + lang_instruction},
        {"role": "user", "content": user_content},
    ]


@app.post("/api/analyze_earnings")
async def analyze_earnings(request: EarningsRequest):
    ticker = request.ticker.strip().upper()
    if not ticker:
        raise HTTPException(status_code=400, detail="Enter a ticker symbol.")

    api_key = validate_header_value(clean_optional_text(request.api_key), "API Key")
    if not api_key:
        api_key = LLM_API_KEY
    if not api_key:
        raise HTTPException(status_code=400, detail="Enter your model API key.")

    report_mode = request.report_mode or ""
    if report_mode in ("kimi_llm", "kimi_k3"):
        base_url = clean_optional_text(request.base_url) or KIMI_BASE_URL
        model = clean_optional_text(request.model) or ("kimi-k3" if report_mode == "kimi_k3" else KIMI_MODEL)
    else:
        base_url = clean_optional_text(request.base_url) or LLM_BASE_URL
        model = clean_optional_text(request.model) or LLM_MODEL
    language = request.language or "en"

    messages = build_earnings_messages(ticker, request.quarter, language)

    def stream():
        try:
            client = OpenAI(api_key=api_key, base_url=base_url)
            kwargs: dict = dict(
                model=model,
                messages=messages,
                stream=True,
                max_tokens=16384,
            )
            if report_mode in ("kimi_llm", "kimi_k3"):
                kwargs["extra_body"] = {"reasoning_effort": KIMI_REASONING_EFFORT}
            response = client.chat.completions.create(**kwargs)
            for chunk in response:
                delta = chunk.choices[0].delta.content
                if delta:
                    yield delta
        except Exception as exc:
            yield f"\n\nEarnings analysis failed: {normalize_model_error(exc)}"

    return StreamingResponse(stream(), media_type="text/markdown; charset=utf-8")


# ──────────────────────────────────────────────
# Post-Earnings Price Move Analysis
# ──────────────────────────────────────────────

def _build_post_earnings_move_prompt() -> str:
    """Build post-earnings move prompt with shared hard rules baseline."""
    return f"""{SHARED_HARD_RULES}

You are a senior equity research analyst specializing in post-earnings price action analysis. Your job is to explain WHY a stock moved after earnings — not just what happened, but the specific factors that drove the market's reaction.

OUTPUT FORMAT: Return a single JSON object. Use **bold** for key numbers and findings.

{{
  "moveVerdict": {{
    "direction": "up|down|flat",
    "magnitude": "-15.2%",
    "impliedMove": "plus-minus 8%",
    "exceededImplied": true,
    "oneLineExplanation": "<one sentence explaining the move>"
  }},
  "primaryDrivers": [
    {{
      "factor": "<factor name>",
      "impact": "high|medium|low",
      "direction": "positive|negative",
      "explanation": "<detailed explanation with **bolded numbers**>"
    }}
  ],
  "earningsVsExpectations": {{
    "eps": {{ "actual": "$0.85", "estimate": "$0.78", "surprise": "+8.97%", "verdict": "beat" }},
    "revenue": {{ "actual": "$25.5B", "estimate": "$24.8B", "surprise": "+2.82%", "verdict": "beat" }},
    "guidance": {{ "status": "raised|maintained|cut|no guidance", "details": "<details>" }},
    "narrative": "<paragraph explaining what the earnings data actually said vs what was expected>"
  }},
  "whatTheMarketFocusedOn": "<paragraph explaining which specific metric the market fixated on. **Bold** the key items.>",
  "technicalContext": {{
    "preEarningsRun": "<how the stock moved into earnings>",
    "optionsImplied": "<what options market was pricing in>",
    "volumeAnalysis": "<volume vs average>"
  }},
  "comparableReactions": [
    {{ "company": "<peer ticker>", "event": "<what happened>", "move": "<stock move>", "relevance": "<why this comparison matters>" }}
  ],
  "forwardImplications": {{
    "shortTerm": "<next 1-4 weeks>",
    "mediumTerm": "<next 1-3 months>",
    "thesisImpact": "<does this change the investment thesis?>"
  }},
  "keyLevels": {{
    "support": "<price level>",
    "resistance": "<price level>",
    "nextCatalyst": "<next event>"
  }}
}}

RULES:
- Explain the move with SPECIFIC numbers, not vague narratives
- primaryDrivers: 3-5 drivers, ranked by impact
- Every comparison must reference a real historical event with a date
- Never use the word "interesting" — be specific about why something matters
- This is DECISION-SUPPORT ONLY. Never auto-trade, never place orders.
- Write professionally, no emoji, evidence-led
- If specific data is unavailable, note it clearly rather than fabricating
"""


def build_post_earnings_move_messages(
    ticker: str,
    move_pct: Optional[float],
    quarter: Optional[str],
    language: str,
) -> list[dict[str, str]]:
    """Build messages for post-earnings price move analysis."""
    quarter_str = quarter or "the most recent quarter"
    move_str = f"The stock moved {move_pct:+.1f}%" if move_pct is not None else "Analyze the stock's post-earnings price movement"

    user_content = (
        f"Analyze the post-earnings price movement of **{ticker}** after {quarter_str} earnings.\n\n"
        f"{move_str}.\n\n"
        f"Search for:\n"
        f"1. The actual earnings results (EPS, revenue, guidance vs expectations)\n"
        f"2. What management said on the earnings call\n"
        f"3. How the stock moved (after-hours, next-day, and subsequent days)\n"
        f"4. Analyst reactions and rating changes\n"
        f"5. Options market implied move vs actual move\n"
        f"6. How peers have moved on similar earnings\n\n"
        f"Explain WHY the market reacted this way. What specific numbers, guidance, or management comments drove the move?\n\n"
        f"Return the analysis as a JSON object following the system prompt schema."
    )

    lang_instruction = ""
    lang_names = {
        "zh-TW": "Traditional Chinese (繁體中文)",
        "zh-CN": "Simplified Chinese (简体中文)",
        "ja": "Japanese (日本語)",
        "ko": "Korean (한국어)",
        "es": "Spanish",
        "de": "German",
        "fr": "French",
        "en": "English",
    }
    if language and language != "en":
        lang_name = lang_names.get(language, language)
        lang_instruction = f"\n\nIMPORTANT: Write the ENTIRE analysis in {lang_name}."

    return [
        {"role": "system", "content": _build_post_earnings_move_prompt() + lang_instruction},
        {"role": "user", "content": user_content},
    ]


@app.post("/api/post_earnings_move")
async def post_earnings_move(request: PostEarningsMoveRequest):
    ticker = request.ticker.strip().upper()
    if not ticker:
        raise HTTPException(status_code=400, detail="Enter a ticker symbol.")

    api_key = validate_header_value(clean_optional_text(request.api_key), "API Key")
    if not api_key:
        api_key = LLM_API_KEY
    if not api_key:
        raise HTTPException(status_code=400, detail="Enter your model API key.")

    report_mode = request.report_mode or ""
    if report_mode in ("kimi_llm", "kimi_k3"):
        base_url = clean_optional_text(request.base_url) or KIMI_BASE_URL
        model = clean_optional_text(request.model) or ("kimi-k3" if report_mode == "kimi_k3" else KIMI_MODEL)
    else:
        base_url = clean_optional_text(request.base_url) or LLM_BASE_URL
        model = clean_optional_text(request.model) or LLM_MODEL
    language = request.language or "en"

    messages = build_post_earnings_move_messages(
        ticker, request.move_pct, request.quarter, language
    )

    def stream():
        try:
            client = OpenAI(api_key=api_key, base_url=base_url)
            kwargs: dict = dict(
                model=model,
                messages=messages,
                stream=True,
                max_tokens=16384,
            )
            if report_mode in ("kimi_llm", "kimi_k3"):
                kwargs["extra_body"] = {"reasoning_effort": KIMI_REASONING_EFFORT}
            response = client.chat.completions.create(**kwargs)
            for chunk in response:
                delta = chunk.choices[0].delta.content
                if delta:
                    yield delta
        except Exception as exc:
            yield f"\n\nPost-earnings analysis failed: {normalize_model_error(exc)}"

    return StreamingResponse(stream(), media_type="text/markdown; charset=utf-8")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="127.0.0.1", port=8000)
