import { BillingPlan } from "../types";

const FREE_FEATURES = {
  REPORTS_3_TOTAL: "REPORTS_3_TOTAL",
  JINA_SEARCH_3_TOTAL: "JINA_SEARCH_3_TOTAL",
  COMPREHENSIVE_LENS: "COMPREHENSIVE_LENS",
  OWN_API_KEY: "OWN_API_KEY",
  MARKDOWN_EXPORT: "MARKDOWN_EXPORT",
} as const;

const PRO_FEATURES = {
  PLATFORM_DEEPSEEK_KEY: "PLATFORM_DEEPSEEK_KEY",
  UNLIMITED_JINA_SEARCH: "UNLIMITED_JINA_SEARCH",
  UNLIMITED_REPORTS: "UNLIMITED_REPORTS",
  ALL_LENSES: "ALL_LENSES",
  REPORT_HISTORY: "REPORT_HISTORY",
  MARKDOWN_EXPORT: "MARKDOWN_EXPORT",
  EMAIL_SUPPORT: "EMAIL_SUPPORT",
} as const;

const BUSINESS_FEATURES = {
  ...PRO_FEATURES,
  TEAM_WORKSPACE: "TEAM_WORKSPACE",
  SHARED_LIBRARY: "SHARED_LIBRARY",
  API_ACCESS: "API_ACCESS",
  CUSTOM_TEMPLATES: "CUSTOM_TEMPLATES",
  BRANDED_PDF: "BRANDED_PDF",
  PRIORITY_SUPPORT: "PRIORITY_SUPPORT",
} as const;

export const FEATURES = {
  [BillingPlan.FREE]: FREE_FEATURES,
  [BillingPlan.PRO]: PRO_FEATURES,
  [BillingPlan.BUSINESS]: BUSINESS_FEATURES,
} as const;

export type Feature =
  | (typeof FREE_FEATURES)[keyof typeof FREE_FEATURES]
  | (typeof PRO_FEATURES)[keyof typeof PRO_FEATURES]
  | (typeof BUSINESS_FEATURES)[keyof typeof BUSINESS_FEATURES];
