/**
 * AUTO-GENERATED by scripts/generate-skill-contract.mjs
 * DO NOT EDIT — edit skills/deep-dive/SKILL.md or skills/filing/SKILL.md instead.
 * Run: pnpm generate:skill-contract
 */

export const DEEP_DIVE_METHODOLOGY = `---
name: deep-dive
description: >
  Generate a full six-lens equity research report on any stock or ticker.
  Use this skill whenever the user asks for a deep dive, full analysis,
  research report, due diligence, a thesis review,
  or any substantive opinion on a listed company — even if they don't say
  "report". Covers six lenses in one pass: Supply Chain, Fundamentals, Macro,
  Technicals, Sentiment, and Risk Matrix. For quick one-screen reads, prefer
  the snapshot skill instead. Decision-support only — never places orders.
---

# Deep Dive — Six-Lens Equity Research Report

Produce ONE integrated report covering ALL SIX lenses below, in this order.
The user does not pick lenses — every Deep Dive includes all of them. Each
lens has a methodology file in \`references/\`; read the relevant file(s)
before writing that section.

| #   | Section                   | Reference file               | Target length |
| --- | ------------------------- | ---------------------------- | ------------- |
| 1   | Supply Chain & Value Flow | \`references/supply-chain.md\` | 300–500 words |
| 2   | Fundamentals              | \`references/fundamentals.md\` | 250–400 words |
| 3   | Macro Context             | \`references/macro.md\`        | 150–300 words |
| 4   | Technicals                | \`references/technicals.md\`   | 150–250 words |
| 5   | Sentiment & Positioning   | \`references/sentiment.md\`    | 150–250 words |
| 6   | Risk Matrix & Conviction  | \`references/risk-matrix.md\`  | 250–400 words |

## Workflow

### Step 0 — Entity Resolution Gate (MANDATORY, blocks everything else)

Before ANY analysis, resolve the input to exactly ONE verified listed
entity. This gate exists because the single worst failure mode of
multi-lens research is each lens silently guessing a different company.

1. **Verify the ticker exists.** If the \`airesearch-data\` MCP server is
   connected, call its \`resolve_entity\` tool — it returns either one
   verified entity (with an entity-lock block) or candidates. Otherwise,
   web-search the input as a ticker symbol and confirm it resolves to a
   currently listed security. "Looks like a ticker" is not verification —
   confirm against a quote page or filing.
2. **If the input is NOT a valid ticker** (a material, industry, product,
   or brand name — e.g. "Liquid Silicone Rubber"), DO NOT coerce it into
   the nearest-looking symbol and DO NOT let any lens guess. Instead:
   - If plausible ticker candidates exist, STOP and ask the user which
     entity they mean, listing candidates with full names and exchanges.
   - If the input is an industry/material/theme, offer Industry Mode
     (below) instead of forcing the single-stock framework.
3. **Emit an Entity Block** and treat it as immutable for the rest of the
   report:

   \`\`\`
   ENTITY: <TICKER> — <full legal name> (<exchange>)
   SECTOR: <sector / industry>
   MKT CAP: <value, as-of date>
   \`\`\`

4. **Ambiguous symbols** (multiple listings, e.g. "SOI"): resolve to one
   and state the choice in the Entity Block; never analyze a blend.

### Steps 1–4

1. **Gather current data** for the Entity Block company only. Prefer the
   \`airesearch-data\` MCP tools when connected: \`get_quote\`,
   \`get_financials\` (GAAP fundamentals), \`get_technicals\` (real computed
   indicators). Use web search for news/filings/contracts, analyst
   coverage, and anything the tools don't cover — and as the full
   fallback when the MCP server is not connected. Never rely on training
   data for prices or recent quarters — theses decay.
2. **Run the six lenses.** Read each reference file, apply it, write the
   section. If subagents are available (Claude Code), you MAY fan out
   lenses 1–5 as parallel subagents — but every subagent prompt MUST begin
   with the verbatim Entity Block and the instruction "analyze ONLY this
   entity; do not re-resolve the ticker; if your lens lacks data for this
   entity, say so rather than substituting a similar company." Lens 6
   (Risk Matrix) must be written LAST by the main agent because it
   integrates the other five.
3. **Reconciliation check (before publishing).** Re-read all six sections
   and verify every company name and ticker mentioned as the subject
   matches the Entity Block. Any section referring to a different entity
   must be rewritten before the report is delivered — never publish and
   caveat.
4. **Write the verdict.** End with a Conviction Summary (see Output format).

## Industry Mode (theme / industry / material queries)

When the input is NOT a valid ticker — it's an industry, material, product
area, or multi-word theme (e.g. "Humanoid robot", "liquid silicone rubber",
"HBM", "grid transformers") — use Industry Mode instead of forcing the
single-stock framework.

### Data source: ETF holdings (preferred)

Theme ETFs are professionally curated lists of listed companies for a
theme, with portfolio weights. If the \`airesearch-data\` MCP server is
connected:

1. Call \`resolve_entity\` on the theme query. If it returns candidates with
   \`quoteType === "ETF"\`, those are theme ETFs.
2. Call \`get_etf_holdings\` for up to 3 ETF candidates. Each returns
   \`{ symbol, name, weightPct }[]\`.
3. Merge holdings across ETFs:
   - Track each constituent's average portfolio weight across ETFs.
   - Track consensus: how many of the theme ETFs hold each name.
   - Sort by consensus descending, then weight descending. Take top 20.
4. The merged list IS the constituent universe. Every company in the
   report must come from this list or from the provided search context —
   never from memory alone.

If no ETF candidates exist or \`get_etf_holdings\` returns empty, fall back
to web-search-only mode (below).

### Web-search-only fallback

When the MCP server is not connected or no theme ETFs are available, use
web search to identify key listed players. Be explicit in the report:
"Constituent list derived from web search — no theme-ETF holdings data
available." Only name companies that appear in the search results; never
from memory alone.

### Cross-market expansion (A-shares / H-shares)

US theme ETFs rarely hold A-shares, so a US-ETF-only universe silently
drops the China-listed leg of most value chains. After building the
primary constituent table, run one expansion pass:

1. For each chain layer, search for A-share / H-share listed peers
   (sources: China-listed theme ETF or index constituent lists, HKEX/
   CNINFO filings, financial-media coverage). Same sourcing rule applies:
   every name must come from holdings data or a citable search result —
   never from memory. Tag each with exchange (SSE/SZSE/HKEX) and how it
   was sourced.
2. Where the data layer resolves the ticker (e.g. \`0700.HK\`, \`600xxx.SS\`),
   pull real multiples and add a **cross-market valuation gap** table:
   same-layer US peer vs A/H peer, same multiple, both period-labeled.
   State the gap as a fact ("trades at 18x TTM vs US peer 45x, a 60%
   discount") and explain the _structural reasons_ for it (liquidity,
   capital controls, governance premium, index inclusion) — this is
   analysis, not a rating.
3. Never write "undervalued, should buy". The compliant form is:
   discount/premium size + period labels + candidate reasons + what would
   close the gap (catalyst) + what keeps it open (risk). Deep Dive offers
   may include A/H names on equal footing with US names.
4. If no sourced A/H peer exists for a layer, say so — an honest "no
   listed A-share pure play found in sources" beats a from-memory guess.

### Output

Produce:

(a) **Value chain map** of the industry (Lens 1 methodology applied to the
sector) — upstream, midstream, downstream layers.
(b) **Constituent table**: key LISTED players per chain layer with tickers,
exchanges, market caps, and (when available) avg portfolio weight and
ETF consensus.
(c) **Bottleneck analysis**: which layers show bottleneck dynamics
(sole-source, pricing power, small % of downstream BOM).
(d) **Cross-market valuation gap** (when A/H peers resolve in the data
layer): same-layer, same-multiple, period-labeled comparison with
structural discount/premium reasons.
(e) **Deep Dive offer**: suggest 2–3 constituents worth a full six-lens
Deep Dive, with a one-line reason for each.

### Hard rules for Industry Mode

- The constituent universe is the ONLY source of company names. Do not
  add companies from memory.
- Do NOT output per-stock technicals, price targets, entry/stop levels,
  or conviction tiers — those require a single-stock Deep Dive.
- If the theme has no ETF data AND no search results, say so. Never
  fabricate a player list.

## Optional focus argument

If the user asks for a single lens (e.g. "/airesearch:deep-dive NVDA risk" or "just
the supply chain view"), produce only that section at 2–3x its target
length, plus the one-line disclaimer. Valid focus values: \`supply-chain\`,
\`fundamentals\`, \`macro\`, \`technicals\`, \`sentiment\`, \`risk\`.

## Output format

- Respond in the user's language; keep tickers, metric names, and section
  data labels in English.
- Structure:
  1. **ENTITY LOCK** (from the resolved entity block; unchanged).
  2. **Three Falsifiable Judgments** — exactly three. Each judgment must
     include one direct sentence, one numeric anchor, supporting evidence,
     and \`Wrong if:\` with a numeric trigger. No number, no judgment.
  3. The six lens sections with \`##\` headers, in the table order above.
     Each lens must end with:
     - \`Lens judgment:\` one numeric, falsifiable conclusion.
     - \`How to read this number:\` source, measurement basis, timestamp/date,
       and known blind spot.
  4. **Thesis Invalidation Conditions** — 2–4 observable signals that would
     force the thesis to be rechecked. These are not recommendations.
  5. **Monitor Panel** — a 3–6 row table:
     \`Metric | Current value | Trigger line | Tolerance | Check frequency | Data source\`
  6. A machine-readable monitor JSON block:

     \`\`\`json
     {
       "schema_version": 1,
       "monitors": [
         {
           "metric": "string",
           "current": "string",
           "trigger": "string",
           "tolerance": "string",
           "freq": "Daily | Weekly | Quarterly | Event-driven",
           "source": "string"
         }
       ]
     }
     \`\`\`

  7. **Conviction Tier** — S/A/B/C/D/F as a thesis-quality score only:
     evidence completeness and logical closure, not whether to buy, sell,
     hold, size, or allocate.
  8. **Disclaimer**.

- Every quantitative claim gets a date or period attached ("Q1 FY26",
  "as of 2026-07-03"). Distinguish facts from estimates from opinion.
- Close with one line: _Decision-support analysis, not financial advice.
  Verify prices and fundamentals before acting._

## Hard rules

- Never fabricate financial figures. If a number can't be verified, say so.
- Fabricating price levels, indicator values (RSI, MACD), support/
  resistance, or entry/stop prices is a CRITICAL failure — worse than an
  empty section. Any section that cannot source real current data must
  say "insufficient data — section withheld" instead of estimating.
- Never analyze an entity that was not confirmed through the Entity
  Resolution Gate; never substitute a similarly-named company.
- GAAP first; if citing non-GAAP, name the excluded items.
- Never present the report as a trade instruction and never execute,
  place, or cancel orders under any circumstances.
- Never output target prices, buy/sell ratings, entry levels, stop levels,
  portfolio weights, position sizing, or personalized investment instructions.`;

export const FILING_METHODOLOGY = `---
name: filing
description: >
  Search and analyze SEC EDGAR filings (10-K, 10-Q, 20-F, 6-K) for any
  US-listed company. Use when the user asks for a company's annual report,
  quarterly filing, earnings release, or any SEC document. Supports two
  modes: Mode A (user provides a filing URL directly) and Mode B (user
  provides a company name → search candidates → user selects → analyze).
  Every numeric claim cites a page number (p.NN) linking back to the
  original filing. Only covers US-listed filers; non-US tickers are
  rejected with a clear reason and exchange hint.
version: 0.5.0
---

# Filing — SEC EDGAR Document Search & Analysis

Search for and analyze SEC filings from US-listed companies. Every numeric
claim cites a page number (\`p.NN\`) linking back to the original document.

## Scope

**Supported**: US-listed filers on SEC EDGAR (10-K, 10-Q, 20-F, 6-K + amendments)
**Not supported**: Hong Kong (HKEX), A-share (CNINFO), or other non-US exchanges

Non-US tickers are rejected at the entity gate with a clear reason and
exchange hint. The skill MUST pass this guidance through to the user
verbatim — never say "no reports found" when the real reason is
"SEC EDGAR only covers US-listed filers."

## Two Modes

### Mode A — Direct Filing (user provides URL or file)

When the user provides a filing URL or document directly:

1. Validate the URL is a SEC domain (\`sec.gov\`, \`efts.sec.gov\`, \`data.sec.gov\`)
2. Call \`fetch_filing_content\` to parse the document
3. If \`isScanned: true\` → tell user OCR is required, do not analyze
4. Analyze with page-number anchors (see Output Format below)

### Mode B — Search & Select (user provides company name)

When the user provides a company name or ticker:

1. **Entity Gate** (MANDATORY):
   - Call \`search_filings\` with the query
   - If the response is \`ok: false\` with a non-US reason → pass the
     guidance message through VERBATIM to the user. Include the exchange
     hint (e.g., "Use HKEX 披露易 for HK filings"). Do NOT say "no
     reports found" — that hides the real reason.
   - If candidates are returned → proceed to step 2

2. **Candidate Selection**:
   - Present candidates to the user: form type, filing date, period ending
   - Default-highlight the most recent filing of the requested type
   - **Wait for user to confirm selection** — never auto-pick
   - If user says "latest" or "newest", use the first candidate

3. **Fetch & Analyze**:
   - Call \`fetch_filing_content\` with the selected filing URL
   - If \`isScanned: true\` → tell user OCR is required
   - Analyze with page-number anchors (see Output Format below)

## MCP Tools

### \`search_filings\`

Search SEC EDGAR for company filings.

**Parameters:**

- \`query\` (string, required): Company name or ticker
- \`forms\` (string[]): Filter by form types, e.g. \`["10-K"]\`, \`["10-Q"]\`
- \`startYear\` / \`endYear\` (number): Date range filter
- \`limit\` (number): Max results (default: 20)

**Returns:** \`{ ok: true, candidates[], totalResults }\` or
\`{ ok: false, reason, message }\`

For non-US queries, the response includes an exchange hint:

\`\`\`
{ ok: false, reason: "no_results",
  message: "\\"0700.HK\\" is a Hong Kong-listed ticker. SEC EDGAR only
  covers US-listed filers. Use HKEX 披露易 for HK filings." }
\`\`\`

### \`fetch_filing_content\`

Fetch and parse a filing's content with page indexing.

**Parameters:**

- \`url\` (string, required): Filing URL from \`search_filings\` (SEC only)

**Returns:** \`{ ok: true, text, pages[], isScanned, contentType }\` or
\`{ ok: false, reason, message }\`

## Output Format

Every filing analysis produces:

### 1. Filing Summary

\`\`\`
FILING: NVIDIA CORP 10-K (FY2025)
PERIOD: Ending Jan 26, 2025
FILED: Feb 26, 2025
SOURCE: SEC EDGAR (p.1–87)
\`\`\`

### 2. Key Changes

3–5 significant changes from the filing, each with:

- What changed
- Why it matters
- Page reference (e.g., "p.35")

### 3. Financial Highlights

Key metrics extracted from the filing, each with:

- Metric name + value + period
- YoY/QoQ change
- Page reference

### 4. Three Falsifiable Judgments

Exactly three \`topJudgments\`, each with:

- \`judgment\` — one falsifiable thesis sentence
- \`keyNumber\` — numeric anchor from the filing
- \`wrongIf\` — numeric condition that invalidates the judgment
- \`dataPoint\` — source + page reference (e.g., "10-K FY2025 p.35")

### 5. Risk Factors

Top risks from the filing, each with severity and page reference.

### 6. Thesis Invalidation Conditions

2–4 observable signals that would force the thesis to be rechecked.

### 7. Monitor Panel

3–6 row table: \`Metric | Current | Trigger | Tolerance | Freq | Source\`

Plus machine-readable JSON:

\`\`\`json
{
  "schema_version": 1,
  "monitors": [
    {
      "metric": "string",
      "current": "string",
      "trigger": "string",
      "tolerance": "string",
      "freq": "Daily | Weekly | Quarterly | Event-driven",
      "source": "string"
    }
  ]
}
\`\`\`

### 8. Conviction Tier

S/A/B/C/D/F — thesis quality score only (evidence completeness and
logical closure), not a buy/sell recommendation.

## L3 Ledger Integration

Top judgments from filing analysis are logged to the L3 Ledger via
\`autoInsertLedgerJudgments\`, same as the existing report flow.

## Scanned PDF Handling

If \`isScanned: true\`:

- Do NOT attempt to analyze the content
- Return: "This filing is a scanned PDF (image-based). OCR processing is
  required to extract text. Please use an OCR service to convert the
  document to text first."
- Do NOT guess or infer content from the filing title/type

## Hard Rules

1. **Never fabricate URLs** — only URLs from SEC API responses
2. **Always return candidates** — never auto-pick; highlight latest but
   user confirms
3. **Page-number anchors** — every \`dataPoint\` cites \`p.XX\` from the filing
4. **Scanned PDF → OCR required** — do not guess content
5. **No full-text storage** — copyright compliance; only parsed results
6. **Non-US guidance is verbatim** — pass through the exchange hint from
   \`search_filings\`, never replace with generic "no reports found"
7. **Never use web search as fallback** for filing data — web search
   returns secondary sources, not primary filings
8. **Never output target prices, buy/sell ratings, entry levels, stop
   levels, portfolio weights, or position sizing**

## Examples

### Mode B: NVDA Annual Report

\`\`\`
User: /airesearch:filing NVDA

→ search_filings({ query: "NVDA", forms: ["10-K"], limit: 5 })
→ Returns 6 candidates, latest: 10-K FY2025 (filed 2026-02-25)

Present to user:
  1. 10-K | 2026-02-25 | FY2025 (Jan 26, 2025)  ← highlighted
  2. 10-K | 2025-02-26 | FY2024 (Jan 28, 2024)
  3. 10-K | 2024-02-21 | FY2023 (Jan 29, 2023)
  ...

User confirms #1
→ fetch_filing_content({ url: "https://www.sec.gov/Archives/..." })
→ Analyze with page anchors
→ Output with "Revenue $130.5B (p.35)" style citations
\`\`\`

### Non-US Rejection: 0700.HK

\`\`\`
User: /airesearch:filing 0700.HK

→ search_filings({ query: "0700.HK" })
→ Returns: { ok: false, reason: "no_results",
    message: "\\"0700.HK\\" is a Hong Kong-listed ticker. SEC EDGAR only
    covers US-listed filers. Use HKEX 披露易 for HK filings." }

Output to user:
  ❌ SEC EDGAR does not cover 0700.HK (Tencent Holdings).

  This ticker is listed on the Hong Kong Stock Exchange (HKEX).
  SEC EDGAR only covers US-listed filers.

  For HK filings, use HKEX 披露易 (hkexnews.hk).

  [Do NOT say "no reports found" or offer web search as fallback]
\`\`\``;

export const SHARED_HARD_RULES = `## SHARED HARD RULES (from analysis contract — applies to ALL modes)

1. **Entity Gate (MANDATORY).** Resolve input to exactly ONE verified listed entity before ANY analysis. Never analyze a blend. If ambiguous, STOP and ask.
2. **Never fabricate financial figures.** If a number can't be verified, say "Data unavailable — [what to verify]".
3. **Never output** target prices, buy/sell ratings, entry levels, stop levels, portfolio weights, position sizing, or personalized investment instructions.
4. **Conviction tier** (S/A/B/C/D/F) evaluates evidence quality only — not whether to buy, sell, hold, size, or allocate.
5. **Every quantitative claim** gets a date or period attached. Distinguish facts from estimates from opinion.
6. **GAAP first.** If citing non-GAAP, name the excluded items.
7. **Never substitute** a similarly-named company. If data is missing for the resolved entity, say so.
8. **Reports end with invalidation conditions**, not price targets.
9. **Never present** the report as a trade instruction. Never execute, place, or cancel orders.
10. **Cross-market A/H peers: sourced or stated absent.** When the methodology
    calls for A-share or H-share peer comparison, every listed peer MUST come
    from search results with a citable source (ETF holdings, filings, financial
    media). If no sourced A/H peer exists for a chain layer, write
    "No listed A-share/H-share pure play found in sources" — never fill the
    gap from memory. **Fabricating peer names is the same failure as
    fabricating financial figures (rule 2).**`;

export const MONITOR_JSON_SCHEMA = `{
  "schema_version": 1,
  "monitors": [
    {
      "metric": "<metric to monitor>",
      "current": "<current value or N/A>",
      "trigger": "<numeric trigger line>",
      "tolerance": "<optional tolerance band or empty string>",
      "freq": "Daily | Weekly | Quarterly | Event-driven",
      "source": "<data source>"
    }
  ]
}`;

export const MODE_PERSPECTIVES = {
  snapshot: {
    label:
      "Investment snapshot: decide in 3 minutes whether the stock deserves deeper work",
    focus:
      "Balance breadth vs depth. Cover thesis, valuation, risks, and catalysts at equal weight. The decisionBrief should answer: does this stock deserve deeper research right now?",
    emphasis: "overview, investmentThesis, decisionBrief",
  },
  earnings: {
    label:
      "Earnings review: focus on growth quality, margins, cash flow, and execution",
    focus:
      "Deep-dive revenue trajectory, margin evolution (gross → operating → net), FCF conversion, and earnings surprise history. Weight growthDrivers and profitability sections 2x heavier than other sections. Include quarter-over-quarter trends and segment breakdowns.",
    emphasis:
      "growthDrivers, profitability, topJudgments (margin/cash flow focus)",
  },
  competition: {
    label:
      "Competitive landscape: moat, substitution risk, pricing power, and industry position",
    focus:
      "Analyze market share trends, moat durability (brand/tech/network/switching cost), Porter's Five Forces summary, peer benchmarking (top 3-5 competitors), and substitution threats. Weight the overview section around competitive dynamics.",
    emphasis:
      "overview (competitive framing), risks (disruption/substitution), scenarioMatrix (market share scenarios)",
  },
  risk: {
    label:
      "Risk scan: valuation, balance sheet, cash flow, cyclicality, and crowded narrative risk",
    focus:
      "Invert the analysis — lead with what can go wrong. Weight risks section 3x: balance sheet fragility, cash flow quality under stress, valuation downside, cyclicality exposure, and narrative crowding. Each risk must have a numeric trigger. The decisionBrief should focus on risk/reward asymmetry.",
    emphasis:
      "risks (primary focus), valuation (downside scenarios), scenarioMatrix (bear case details)",
  },
  poc: {
    label:
      "Tracking plan: convert the thesis into 30-90 day measurable validation points",
    focus:
      "Focus on the watchlist and monitorPanel sections. For each thesis driver, define: (1) a specific metric to track, (2) current value, (3) trigger threshold, (4) data source, (5) check frequency. The decisionBrief should outline a 30-90 day monitoring cadence. Light on narrative, heavy on actionable metrics.",
    emphasis: "watchlist, monitorPanel, nextSteps, evidenceNeeds",
  },
} as const;

export type AnalysisMode = keyof typeof MODE_PERSPECTIVES;
